# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='skillset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=400)),
                ('second', models.CharField(max_length=400)),
                ('third', models.CharField(max_length=400)),
            ],
        ),
    ]
